### ISSUE TITLE
INFO] optimization couldn't satisfy all constraints when roslaunch tesseract_ros_examples puzzle_piece_auxillary_axes_example.launch 

### ISSUE THREAD

**Issue by dbdxnuliba** [tesseract-robotics/tesseract_ros#176]
roslaunch tesseract_ros_examples puzzle_piece_auxillary_axes_example.launch 

INFO] optimization couldn't satisfy all constraints
Info:    TRAJOPT motion planning failed (Failed to find valid solution) for process input: Tesseract Composite Instruction
Debug:   worker 4 finished running TRAJOPT
Debug:   worker 0 ready to run Error Callback
![tesseract_puzzle](https://user-images.githubusercontent.com/13350158/190942402-004ce091-c0a9-48e9-aa3c-5a965f851c23.gif)

**Comment by Levi-Armstrong** [comment]
Are you running 0.13.X version?

**Comment by dbdxnuliba** [comment]
it's 0.12.0

**Comment by Levi-Armstrong** [comment]
Interesting. I will see if I can track down the release where it broke.

**Comment by Levi-Armstrong** [comment]
This was broken when we switched OSQP to enable adaptive_rho by default which in most cases speeds up convergences, but in this case it prevents it from converging. I am exposing the convex solver config in the trajopt solver profile so this can be disabled.

**Comment by Levi-Armstrong** [comment]
Fixed by recent PR.

**Comment by Levi-Armstrong** [comment]
> where can I modify the config param
> 
> > This was broken when we switched OSQP to enable adaptive_rho by default which in most cases speeds up convergences, but in this case it prevents it from converging. I am exposing the convex solver config in the trajopt solver profile so this can be disabled.

Here is what I had to modify

https://github.com/tesseract-robotics/tesseract_planning/blob/00726c502b3a71c2df02576e0012037884e4ef6a/tesseract_examples/src/puzzle_piece_auxillary_axes_example.cpp#L211-L218
