### ISSUE TITLE
catkin build err,tesseract_planning-0.13.0,tesseract_planning-0.13.0/tesseract_motion_planners/descartes/src/profile/descartes_default_plan_profile.cpp:31:16:   required from here /usr/include/c++/9/ext/new_allocator.h:146:4: error: invalid new-expression of abstract class type 'descartes_light::StateEvaluator<float>'

### ISSUE THREAD

**Issue by dbdxnuliba** [tesseract-robotics/tesseract_ros#181]
my env:
ubuntu20.04 
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 
catkin build -j3
pkg :tesseract_planning-0.13.0

/home/taimi/ws_tesseract_060/src/tesseract_planning-0.13.0/tesseract_motion_planners/descartes/src/profile/descartes_default_plan_profile.cpp:31:16:   required from here
/usr/include/c++/9/ext/new_allocator.h:146:4: error: invalid new-expression of abstract class type 'descartes_light::StateEvaluator<float>'
  146 |  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }
![image](https://user-images.githubusercontent.com/13350158/191942626-f243ea2f-60e4-48a3-bba7-0db2889a40cf.png)

**Comment by Levi-Armstrong** [comment]
Also if you are building tesseract from source there is a know issue with having it install as binary. So I would remove ros-noetic-tesseract*

**Comment by vegfood** [comment]
> my env: ubuntu20.04 gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) catkin build -j3 pkg :tesseract_planning-0.13.0
> 
> /home/taimi/ws_tesseract_060/src/tesseract_planning-0.13.0/tesseract_motion_planners/descartes/src/profile/descartes_default_plan_profile.cpp:31:16: required from here /usr/include/c++/9/ext/new_allocator.h:146:4: error: invalid new-expression of abstract class type 'descartes_light::StateEvaluator' 146 | { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); } ![image](https://user-images.githubusercontent.com/13350158/191942626-f243ea2f-60e4-48a3-bba7-0db2889a40cf.png)

I have encountered the same problem as mentioned above with descartes_light version 0.3.0. After I checkout current master HEAD of descates_light (rev. fbb74ebe679ba21cf1a49d4f7b5e353da75f0549), the error disappears.

**Comment by dbdxnuliba** [comment]
> Can you provide the versions of descates, tesseract, tesseract_planning, tesseract_ros, tesseract_qt that you are using?

descartes_light version 0.3.0,tesseract-0.13.1,tesseract_planning-0.13.0,tesseract_ros0.6.0,tesseract_qt-0.13.0

**Comment by dbdxnuliba** [comment]
@vegfood ,yes it is, we fix the issue by using descartes_light current master HEAD of descates_light (rev. fbb74ebe679ba21cf1a49d4f7b5e353da75f0549),

> > my env: ubuntu20.04 gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) catkin build -j3 pkg :tesseract_planning-0.13.0
> > /home/taimi/ws_tesseract_060/src/tesseract_planning-0.13.0/tesseract_motion_planners/descartes/src/profile/descartes_default_plan_profile.cpp:31:16: required from here /usr/include/c++/9/ext/new_allocator.h:146:4: error: invalid new-expression of abstract class type 'descartes_light::StateEvaluator' 146 | { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); } ![image](https://user-images.githubusercontent.com/13350158/191942626-f243ea2f-60e4-48a3-bba7-0db2889a40cf.png)
> 
> I have encountered the same problem as mentioned above with descartes_light version 0.3.0. After I checkout current master HEAD of descates_light (rev. fbb74ebe679ba21cf1a49d4f7b5e353da75f0549), the error disappears.

**Comment by dbdxnuliba** [comment]
you can close the issue now thanks
