### ISSUE TITLE
TRAJOPT motion planning failed (Failed to find valid solution) for process input: Tesseract Composite Instruction roslaunch tesseract_ros_examples puzzle_piece_auxillary_axes_example.launch

### ISSUE THREAD

**Issue by dbdxnuliba** [tesseract-robotics/tesseract_ros#184]
![tesseract_pullzel_error](https://user-images.githubusercontent.com/13350158/196596664-348b980e-6ec4-48e5-8481-b1379be8a3fe.gif)

Info:    TRAJOPT motion planning failed (Failed to find valid solution) for process input: Tesseract Composite Instruction
Debug:   worker 0 finished running TRAJOPT
Debug:   worker 0 ready to run Error Callback
Error:   TrajOptTaskflow Failure: 
         at line 51 in /home/taimi/ws_tesseract_060/src/tesseract_planning-0.13.0/tesseract_process_managers/src/core/utils.cpp
Debug:   worker 0 finished running Error Callback

env:
ubuntu20.04,noetic
tesseract_planning-0.13.0
where can I modify the related param like you mentioned in 
https://github.com/tesseract-robotics/tesseract_ros/issues/176

I modify the param in osqp_interface.cpp ,is there any ros param in config file to set the param
![image](https://user-images.githubusercontent.com/13350158/196602245-cf243cb9-b20c-4daf-9b22-ae3842faa940.png)

**Comment by Levi-Armstrong** [comment]
I think that should be it.

**Comment by dbdxnuliba** [comment]
OK,it works  well
