### ISSUE TITLE
How to make the robot move like gif shown?

### ISSUE THREAD

**Issue by Wuqiqi123** [tesseract-robotics/tesseract_ros#220]
I'm new to tesseract. I build tesseract_ros2 by source and launch the demos
```ros2 launch tesseract_ros_examples car_seat_example.launch```, but everything is static.
![image](https://github.com/tesseract-robotics/tesseract_ros/assets/37368540/6cbc93a8-b540-438c-ba66-8ef14858c781)
How can I make the robot moves like gif showing in README?

**Comment by rjoomen** [comment]
Go to the Trajectory tab, select a Trajectory Set and press the play button below the trajectory set list.

**Comment by Wuqiqi123** [comment]
> Go to the Trajectory tab, select a Trajectory Set and press the play button below the trajectory set list.

Thanks!
