### ISSUE TITLE
error: no matching function for call to ‘tesseract_planning::ProfileDictionary::addProfile()

### ISSUE THREAD

**Issue by CodingHzx** [tesseract-robotics/tesseract_ros#259]
Errors     << tesseract_planning_server:make /home/aiwen/15b/ws_tessss/logs/tesseract_planning_server/build.make.003.log
/home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp: In member function ‘void tesseract_planning_server::TesseractPlanningServer::Implementation::loadDefaultPlannerProfiles()’:
/home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:168:97: error: no matching function for call to ‘tesseract_planning::ProfileDictionary::addProfile(const string&, const string&, std::shared_ptr<tesseract_planning::SimplePlannerLVSNoIKPlanProfile>)’
  168 |                          std::make_shared<tesseract_planning::SimplePlannerLVSNoIKPlanProfile>());
      |                                                                                                 ^
In file included from /home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:81:
/home/aiwen/15b/ws_tessss/devel/include/tesseract_command_language/profile_dictionary.h:124:8: note: candidate: ‘template<class ProfileType> void tesseract_planning::ProfileDictionary::addProfile(const string&, const string&, std::shared_ptr<const _Tp>)’
  124 |   void addProfile(const std::string& ns, const std::string& profile_name, std::shared_ptr<const ProfileType> profile)
      |        ^~~~~~~~~~
/home/aiwen/15b/ws_tessss/devel/include/tesseract_command_language/profile_dictionary.h:124:8: note:   template argument deduction/substitution failed:
/home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:168:97: note:   types ‘const _Tp’ and ‘tesseract_planning::SimplePlannerLVSNoIKPlanProfile’ have incompatible cv-qualifiers
  168 |                          std::make_shared<tesseract_planning::SimplePlannerLVSNoIKPlanProfile>());
      |                                                                                                 ^
/home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:174:91: error: no matching function for call to ‘tesseract_planning::ProfileDictionary::addProfile(const string&, const string&, std::shared_ptr<tesseract_planning::TrajOptDefaultPlanProfile>)’
  174 |                          std::make_shared<tesseract_planning::TrajOptDefaultPlanProfile>());
      |                                                                                           ^
In file included from /home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:81:
/home/aiwen/15b/ws_tessss/devel/include/tesseract_command_language/profile_dictionary.h:124:8: note: candidate: ‘template<class ProfileType> void tesseract_planning::ProfileDictionary::addProfile(const string&, const string&, std::shared_ptr<const _Tp>)’
  124 |   void addProfile(const std::string& ns, const std::string& profile_name, std::shared_ptr<const ProfileType> profile)
      |        ^~~~~~~~~~
/home/aiwen/15b/ws_tessss/devel/include/tesseract_command_language/profile_dictionary.h:124:8: note:   template argument deduction/substitution failed:
/home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:174:91: note:   types ‘const _Tp’ and ‘tesseract_planning::TrajOptDefaultPlanProfile’ have incompatible cv-qualifiers
  174 |                          std::make_shared<tesseract_planning::TrajOptDefaultPlanProfile>());
      |                                                                                           ^
/home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:177:96: error: no matching function for call to ‘tesseract_planning::ProfileDictionary::addProfile(const string&, const string&, std::shared_ptr<tesseract_planning::TrajOptDefaultCompositeProfile>)’
  177 |                          std::make_shared<tesseract_planning::TrajOptDefaultCompositeProfile>());
      |                                                                                                ^
In file included from /home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:81:
/home/aiwen/15b/ws_tessss/devel/include/tesseract_command_language/profile_dictionary.h:124:8: note: candidate: ‘template<class ProfileType> void tesseract_planning::ProfileDictionary::addProfile(const string&, const string&, std::shared_ptr<const _Tp>)’
  124 |   void addProfile(const std::string& ns, const std::string& profile_name, std::shared_ptr<const ProfileType> profile)
      |        ^~~~~~~~~~
/home/aiwen/15b/ws_tessss/devel/include/tesseract_command_language/profile_dictionary.h:124:8: note:   template argument deduction/substitution failed:
/home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:177:96: note:   types ‘const _Tp’ and ‘tesseract_planning::TrajOptDefaultCompositeProfile’ have incompatible cv-qualifiers
  177 |                          std::make_shared<tesseract_planning::TrajOptDefaultCompositeProfile>());
      |                                                                                                ^
/home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:180:93: error: no matching function for call to ‘tesseract_planning::ProfileDictionary::addProfile(const string&, const string&, std::shared_ptr<tesseract_planning::TrajOptDefaultSolverProfile>)’
  180 |                          std::make_shared<tesseract_planning::TrajOptDefaultSolverProfile>());
      |                                                                                             ^
In file included from /home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:81:
/home/aiwen/15b/ws_tessss/devel/include/tesseract_command_language/profile_dictionary.h:124:8: note: candidate: ‘template<class ProfileType> void tesseract_planning::ProfileDictionary::addProfile(const string&, const string&, std::shared_ptr<const _Tp>)’
  124 |   void addProfile(const std::string& ns, const std::string& profile_name, std::shared_ptr<const ProfileType> profile)
      |        ^~~~~~~~~~
/home/aiwen/15b/ws_tessss/devel/include/tesseract_command_language/profile_dictionary.h:124:8: note:   template argument deduction/substitution failed:
/home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:180:93: note:   types ‘const _Tp’ and ‘tesseract_planning::TrajOptDefaultSolverProfile’ have incompatible cv-qualifiers
  180 |                          std::make_shared<tesseract_planning::TrajOptDefaultSolverProfile>());
      |                                                                                             ^
/home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:187:96: error: no matching function for call to ‘tesseract_planning::ProfileDictionary::addProfile(const string&, const string&, std::shared_ptr<tesseract_planning::TrajOptIfoptDefaultPlanProfile>)’
  187 |                          std::make_shared<tesseract_planning::TrajOptIfoptDefaultPlanProfile>());
      |                                                                                                ^
In file included from /home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:81:
/home/aiwen/15b/ws_tessss/devel/include/tesseract_command_language/profile_dictionary.h:124:8: note: candidate: ‘template<class ProfileType> void tesseract_planning::ProfileDictionary::addProfile(const string&, const string&, std::shared_ptr<const _Tp>)’
  124 |   void addProfile(const std::string& ns, const std::string& profile_name, std::shared_ptr<const ProfileType> profile)
      |        ^~~~~~~~~~
/home/aiwen/15b/ws_tessss/devel/include/tesseract_command_language/profile_dictionary.h:124:8: note:   template argument deduction/substitution failed:
/home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:187:96: note:   types ‘const _Tp’ and ‘tesseract_planning::TrajOptIfoptDefaultPlanProfile’ have incompatible cv-qualifiers
  187 |                          std::make_shared<tesseract_planning::TrajOptIfoptDefaultPlanProfile>());
      |                                                                                                ^
/home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:190:101: error: no matching function for call to ‘tesseract_planning::ProfileDictionary::addProfile(const string&, const string&, std::shared_ptr<tesseract_planning::TrajOptIfoptDefaultCompositeProfile>)’
  190 |                          std::make_shared<tesseract_planning::TrajOptIfoptDefaultCompositeProfile>());
      |                                                                                                     ^
In file included from /home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:81:
/home/aiwen/15b/ws_tessss/devel/include/tesseract_command_language/profile_dictionary.h:124:8: note: candidate: ‘template<class ProfileType> void tesseract_planning::ProfileDictionary::addProfile(const string&, const string&, std::shared_ptr<const _Tp>)’
  124 |   void addProfile(const std::string& ns, const std::string& profile_name, std::shared_ptr<const ProfileType> profile)
      |        ^~~~~~~~~~
/home/aiwen/15b/ws_tessss/devel/include/tesseract_command_language/profile_dictionary.h:124:8: note:   template argument deduction/substitution failed:
/home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:190:101: note:   types ‘const _Tp’ and ‘tesseract_planning::TrajOptIfoptDefaultCompositeProfile’ have incompatible cv-qualifiers
  190 |                          std::make_shared<tesseract_planning::TrajOptIfoptDefaultCompositeProfile>());
      |                                                                                                     ^
/home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:197:101: error: no matching function for call to ‘tesseract_planning::ProfileDictionary::addProfile(const string&, const string&, std::shared_ptr<tesseract_planning::DescartesDefaultPlanProfile<double> >)’
  197 |                          std::make_shared<tesseract_planning::DescartesDefaultPlanProfile<double>>());
      |                                                                                                     ^
In file included from /home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:81:
/home/aiwen/15b/ws_tessss/devel/include/tesseract_command_language/profile_dictionary.h:124:8: note: candidate: ‘template<class ProfileType> void tesseract_planning::ProfileDictionary::addProfile(const string&, const string&, std::shared_ptr<const _Tp>)’
  124 |   void addProfile(const std::string& ns, const std::string& profile_name, std::shared_ptr<const ProfileType> profile)
      |        ^~~~~~~~~~
/home/aiwen/15b/ws_tessss/devel/include/tesseract_command_language/profile_dictionary.h:124:8: note:   template argument deduction/substitution failed:
/home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:197:101: note:   types ‘const _Tp’ and ‘tesseract_planning::DescartesDefaultPlanProfile<double>’ have incompatible cv-qualifiers
  197 |                          std::make_shared<tesseract_planning::DescartesDefaultPlanProfile<double>>());
      |                                                                                                     ^
/home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:204:88: error: no matching function for call to ‘tesseract_planning::ProfileDictionary::addProfile(const string&, const string&, std::shared_ptr<tesseract_planning::OMPLDefaultPlanProfile>)’
  204 |                          std::make_shared<tesseract_planning::OMPLDefaultPlanProfile>());
      |                                                                                        ^
In file included from /home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:81:
/home/aiwen/15b/ws_tessss/devel/include/tesseract_command_language/profile_dictionary.h:124:8: note: candidate: ‘template<class ProfileType> void tesseract_planning::ProfileDictionary::addProfile(const string&, const string&, std::shared_ptr<const _Tp>)’
  124 |   void addProfile(const std::string& ns, const std::string& profile_name, std::shared_ptr<const ProfileType> profile)
      |        ^~~~~~~~~~
/home/aiwen/15b/ws_tessss/devel/include/tesseract_command_language/profile_dictionary.h:124:8: note:   template argument deduction/substitution failed:
/home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_planning_server/src/tesseract_planning_server.cpp:204:88: note:   types ‘const _Tp’ and ‘tesseract_planning::OMPLDefaultPlanProfile’ have incompatible cv-qualifiers
  204 |                          std::make_shared<tesseract_planning::OMPLDefaultPlanProfile>());
      |                                                                                        ^
make[2]: *** [CMakeFiles/tesseract_planning_server.dir/build.make:63：CMakeFiles/tesseract_planning_server.dir/src/tesseract_planning_server.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:243：CMakeFiles/tesseract_planning_server.dir/all] 错误 2
make: *** [Makefile:141：all] 错误 2
cd /home/aiwen/15b/ws_tessss/build/tesseract_planning_server; catkin build --get-env tesseract_planning_server | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

...............................................................................
Failed     << tesseract_planning_server:make                  [ Exited with code 2 ]
Failed    <<< tesseract_planning_server                       [ 8.1 seconds ]  
__________________________________________________________________________________________________________________________________________________________________________________________________________
Warnings   << tesseract_ros_examples:cmake /home/aiwen/15b/ws_tessss/logs/tesseract_ros_examples/build.cmake.000.log                                                                                      
CMake Warning (dev) at /usr/lib/x86_64-linux-gnu/cmake/assimp-5.0/assimpTargets.cmake:54 (if):
  if given arguments:

    "ON"

  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
Call Stack (most recent call first):
  /usr/lib/x86_64-linux-gnu/cmake/assimp-5.0/assimp-config.cmake:1 (include)
  /home/aiwen/15b/ws_tessss/devel/lib/cmake/tesseract_geometry/Findassimp.cmake:1 (find_package)
  /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /home/aiwen/15b/ws_tessss/devel/lib/cmake/tesseract_geometry/tesseract_geometry-config.cmake:29 (find_dependency)
  /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /home/aiwen/15b/ws_tessss/devel/lib/cmake/tesseract_collision/core-config.cmake:13 (find_dependency)
  /home/aiwen/15b/ws_tessss/devel/lib/cmake/tesseract_collision/tesseract_collision-config.cmake:49 (include)
  /usr/share/cmake-3.16/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /home/aiwen/15b/ws_tessss/devel/lib/cmake/tesseract_environment/tesseract_environment-config.cmake:37 (find_dependency)
  CMakeLists.txt:9 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

** WARNING ** io features related to pcap will be disabled
** WARNING ** io features related to png will be disabled
** WARNING ** io features related to libusb-1.0 will be disabled
cd /home/aiwen/15b/ws_tessss/build/tesseract_ros_examples; catkin build --get-env tesseract_ros_examples | catkin env -si  /usr/bin/cmake /home/aiwen/15b/ws_tessss/src/tesseract_ros/tesseract_ros_examples --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/home/aiwen/15b/ws_tessss/devel/.private/tesseract_ros_examples -DCMAKE_INSTALL_PREFIX=/home/aiwen/15b/ws_tessss/install; cd -

..........................................................................................................................................................................................................
Finished  <<< tesseract_ros_examples                          [ 2 minutes and 2.0 seconds ]                                                                                                               
[build] Summary: 41 of 42 packages succeeded.                                                                                                                                                             
[build]   Ignored:   None.                                                                                                                                                                                
[build]   Warnings:  1 packages succeeded with warnings.                                                                                                                                                  
[build]   Abandoned: None.                                                                                                                                                                                
[build]   Failed:    1 packages failed.                                                                                                                                                                   
[build] Runtime: 2 minutes and 20.8 seconds total.                                                                                                                                                        
aiwen@aiwen:~/15b/ws_tessss$

**Comment by Levi-Armstrong** [comment]
We recently made change. Do you have the latest commits for all of the tesseract repos?

**Comment by CodingHzx** [comment]
Thank you. I have installed the latest versions of **tesseract**, **tesseract_ros**, and **trajopt**, but the packages in `dependencies_unstable.rosinstall` are not up to date. I am now compiling with all the latest versions of the required packages.

**Comment by CodingHzx** [comment]
![2024-12-11 22-36-53屏幕截图](https://github.com/user-attachments/assets/fa9c35c6-a2c4-40b7-8e48-35745c8fe4a9)
![2024-12-11 22-43-16屏幕截图](https://github.com/user-attachments/assets/420e4ed8-28f3-4e9e-a11b-844ccb2acccc)

**Comment by CodingHzx** [comment]
Hello, I just compiled using the following package versions on Ubuntu 20.04 with `catkin build`, and encountered the following errors:

**Comment by CodingHzx** [comment]
Thank you, the compilation was successfully completed. However, when launching the file using `roslaunch tesseract_ros_examples online_planning_example.launch`, the content displayed in RViz is different from the GIF image. Could you please advise what might be causing this issue? Thank you.
![2024-12-11 22-36-53屏幕截图](https://github.com/user-attachments/assets/0a87f3b8-7eb6-4f6e-a120-128ab1b2a024)

error：
![2024-12-11 22-59-04屏幕截图](https://github.com/user-attachments/assets/e1b99a1f-a952-406c-9912-565aba6767be)

**Comment by CodingHzx** [comment]
![2024-12-11 23-58-27屏幕截图](https://github.com/user-attachments/assets/19bc5ed9-c36f-4417-b110-7753c1562223)

it is no use,i do not know how to slove it 【https://github.com/tesseract-robotics/trajopt/issues/305 】

**Comment by Levi-Armstrong** [comment]
The GUI interface have changed since these were create. When the example pauses go to the trajectory tab and play the trajectory to see it execute.

**Comment by CodingHzx** [comment]
![2024-12-12 10-05-30屏幕截图](https://github.com/user-attachments/assets/9f2a086a-085e-44d2-98f2-b790dc39e9ec)
problem resolved, thank you so much for your help!

**Comment by CodingHzx** [comment]
problem resolved, thank you so much for your help!
![2024-12-12 10-05-30屏幕截图](https://github.com/user-attachments/assets/b47d011a-5f05-4195-882c-4f4e935e93db)
